### ISSUE TITLE
remoteimage frontend problem

### ISSUE THREAD

**Issue by Mosolyalbum** [asikart/remoteimage#28] opened 2014-12-11 14:19 UTC
Hy!

I started using remoteimage wich is famous, but now on frontend editing the remoteimage button lost, and the "built in" image button shows me 404 page. What could be the problem?

Thanks, 

Mosolyalbum

**Comment by asika32764** [comment] 2015-01-05 04:22
Hi, is this issue any update?

Could you provide me about your Joomla verison and system information?

**Comment by asika32764** [comment] 2015-01-05 06:48
Sorry, I cannot reproduce this issue, could you provide me a screenshot?

Or please install in a new pure Joomla to check it is not a conflict between plugins.

**Comment by Mosolyalbum** [comment] 2015-01-05 11:05
Hi and thanks for response!

I'm still having this issue. I'm using Joomla 3.3.6, and I was thinking about the problem started right after I moved the site to another server.

Here is a screenshot from the frontend:

![remoteimage](https://cloud.githubusercontent.com/assets/10155426/5612306/0a754c2c-94d3-11e4-9343-fc36ef3c404a.png)

**Comment by Mosolyalbum** [comment] 2015-01-05 11:10
Update...

Remoteimage works on backend. 

It would be awsome if it could work on frontend too. :)

**Comment by asika32764** [comment] 2015-01-05 11:40
It's seems that this error occurred on component page.

Could you change language to en-GB that I can know what happend

**Comment by Mosolyalbum** [comment] 2015-01-05 13:53
I've changed the lenguage to en, but it's the same:

![remoteimage_en](https://cloud.githubusercontent.com/assets/10155426/5613851/a11740ce-94ea-11e4-8cda-464fb85f3007.png)

**Comment by asika32764** [comment] 2015-01-05 14:18
There is too few information to determine the reason.

I guess it maybe caused by user authorise or plugin confliction, could you install Remoteimage in a new Joomla site to test?

**Comment by Mosolyalbum** [comment] 2015-01-05 15:04
You are right!

I tried with admin rights and everything is OK. 

Is it any solution to remote image be able for registered users too?

**Comment by asika32764** [comment] 2015-01-05 15:20
Try to open the "core.manage" access for "Registered" group in Remoteimage configuration.

I haven't did that yet, you can try it.

**Comment by Mosolyalbum** [comment] 2015-01-05 19:17
Sorry, it doesn't work. I've tried to give access for everything (frontend access was disabled), but it's the same. :(

**Comment by asika32764** [comment] 2015-01-06 03:12
I think it has fixed in 2.0.3, please try it.

**Comment by charlesknightsbridge** [comment] 2015-01-09 16:56
I haven’t tried it. As long as the front end component or plugin requires access to files in the administrator folder, I cannot use this extension. On my site, the administrator folder is only accessible to the superuser and managers (via password), so front-end view of images is not possible.


On January 5, 2015 at 10:12:32 PM, Simon Asika (notifications@github.com) wrote:

I think it has fixed in 2.0.3, please try it.

**Comment by asika32764** [comment] 2015-03-11 14:53
Should work in [2.0.4](https://github.com/asikart/remoteimage/releases/tag/2.0.4)

**Closed by asika32764** 2015-03-11 14:53 UTC
Labels: bug
